package com.wiki.monowiki.audit.model;

public enum AuditEventType {
    SPACE_CREATED,

    ARTICLE_CREATED,
    ARTICLE_TITLE_UPDATED,
    ARTICLE_ARCHIVED,
    ARTICLE_UNARCHIVED,

    VERSION_ADDED,

    REVIEW_SUBMITTED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,

    TAG_ADDED_TO_ARTICLE,
    TAG_REMOVED_FROM_ARTICLE,

    COMMENT_ADDED
}